[package]
name = "builder-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-apis-common = { path = "../common" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
types.workspace = true
